image: python

before_script:
- python -m ensurepip --upgrade
- pip install --upgrade 'tox >= 3.14.0'

python36:
  image: python:3.6
  script: tox -e py36

python37:
  image: python:3.7
  script: tox -e py37

python38:
  image: python:3.8
  script: tox -e py38,static,publish
