image: python

before_script:
- python -m ensurepip --upgrade
- pip install --upgrade 'tox ~= 3.7.0'

python35:
  image: python:3.5
  script: tox -e py35

python36:
  image: python:3.6
  script: tox -e py36

python37:
  image: python:3.7
  script: tox -e py37
